projects:
  amplifyapp:
    schemaPath: amplify/backend/api/amplifyapp/build/schema.graphql
    includes:
      - src/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src
        region: ap-southeast-1
        apiId: null
        maxDepth: 2
